server:
  port: 9003
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.199:3306/seata_client_second?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
mybatis-plus:
  configuration:
    # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性
    map-underscore-to-camel-case: true
    # 日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: assign_id
seata:
  # 这里定义seata服务分组名称，必须和下面的seata.service.vgroup-mapping对应，否则将无法获取seata服务端IP信息
  tx-service-group: second-seata-service-group
  registry:
    type: nacos
    nacos:
      server-addr: nacos:8848
      namespace: 18d864b2-80c2-413a-a6d6-26c03c969f0e
      application: seata-server
      group: SEATA_GROUP
  service:
    # seata服务端的地址和端口信息，多个使用英文分号分隔
    vgroup-mapping:
      second-seata-service-group: default
