server:
  port: 9005
spring:
  kafka:
    bootstrap-servers: 192.168.2.198:9092
    # 消费者配置
    consumer:
      # 消费者客户端Id
      client-id: ${spring.application.name}-consumer
      autoCommitInterval: 1000
      # 当偏移量不存在时， 自动重置到最近的偏移
      auto-offset-reset: latest
      # 是否自动提交偏移量
      enable-auto-commit: true
      # key 序列化器
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value 序列化器
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      # 默认消费组Id
      groupId: defaultConsumerGroup
      properties:
        # 消费请求超时时间
        request:
          timeout:
            ms: 40000
        # 消费会话超时时间(超过这个时间consumer没有发送心跳,就会触发rebalance操作)
        session:
          timeout:
            ms: 40000
        # 反序列化时，类型转换受信任的包
        spring:
          json:
            trusted:
              packages: '*'
